### ISSUE TITLE
Problem with mpar%rev

### ISSUE THREAD

**Issue by kostyfisik** [wave-scattering/amos-try#12]
---------- Forwarded message ---------
From: Alexander Moroz <wavescattering@yahoo.com>
Date: Sun, 9 Feb 2020 at 08:22
Subject: Re: any advice where the value of rev = mpar%rev is set ?
To: Konstantin Ladutenko <k.ladutenko@metalab.ifmo.ru>

Note that with R(I):=r^2(\theta)
and with
c_min = 100.0
c_max = 100.0
a = 100.0001
in default.ini I don't understand why one gets rev=114.47150056960329 in rsp_spheroid
and the code returns in tmatr

r(i)=13103.73317847153

???

If I set 
c_min = 10.0
c_max = 10.0
a = 10.0001
in default.ini, 

one gets still rev=114.47150056960329 in rsp_spheroid and still r(i)=13103.70809172221 in tmatr_???

Any explanation for it?

**Comment by kostyfisik** [comment]
@wvstring At the moment https://github.com/wave-scattering/amos-try/blob/master/cylinder2mod/axspartclnew4.f90#L1417 sets rev (and later on mpar%rev in the beginning of apml subroutine) to be the equivalent sphere radius of cylinder volume.

**Comment by kostyfisik** [comment]
As of after https://github.com/wave-scattering/amos-try/commit/3a29901e732dcb4a6a970b77360918e7199fbffd it seems to work much better for the case of sphere.
It still need to be improved for the case of other particles shape, at the moment is is only correct for spheroid and for cylinder.

**Comment by kostyfisik** [comment]
@wvstring Is it solved now?

**Comment by wvstring** [comment]
Yes resolved! ... and it looks that I've finally found the bug preventing me to finalize the LeRu option. Just pushed amended 
tmatr_leru showing overlap of zq11 and qr, qi entries when breakpoint is set on l. 3750!!!!


     On Wednesday, February 19, 2020, 07:30:57 AM EST, Konstantin Ladutenko <notifications@github.com> wrote:  
 
 
@wvstring Is it solved now?

**Comment by kostyfisik** [comment]
Ok, let me know if you need any help, I should be able to find a couple of
spare hours during the weekend.
